#!/bin/bash
#
#echo current date and commit
cd "$SECOND_BRAIN"
line_count=$(find . -maxdepth 1 -type f -name '*.png' | wc -l)

if [ "$line_count" -ne 0 ]; then
	mv *.png ./media
	echo "moved images to the media folder"
fi

date_commit=$(date +"%Y/%m/%d %H:%M:%S")
commit_msg="vault backup: ${date_commit}"

git pull origin main
git add .
git commit -m "${commit_msg}"
git push origin main
