#!/bin/bash

#TODO: WIP, not use for production mode
#add to describe resources
#delet resources
#build a common function instead of one function per reosource in Kubernetes

# context resources
set_context() {
	kubectl config use-context $(kubectl config get-contexts -o name | fzf)
}

# namespace resources
set_namespace() {
	kubectl config set-context --current --namespace=$(kubectl get namespace --output=jsonpath='{range .items[*]}{.metadata.name}{"\n"}' | fzf)
}

describ_pod() {
	kubectl describe pods/$pod
}

log_forward_pod() {
	kubectl logs -f pods/$pod
}

log_pod_line() {
	kubectl logs --tail=$1 pods/$pod
}

if [[ -n $1 ]]; then
	case "$1" in
	"ctx")
		set_context
		;;
	"ns")
		set_namespace
		;;
	*)
		echo "hello"
		;;
	esac
fi
