# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  CTN: '{{ .CTN | default "podman" }}'
  USER_DIR: '{{ .USER_DIR | default "/var/home/doku" }}'

includes:
  install: 'dotfiles/taskfile/install.yaml'
  gh: 'dotfiles/taskfile/gh.yaml'
  sync: 'dotfiles/taskfile/sync.yaml'
  ctn: 'dotfiles/taskfile/container.yaml'

tasks:
  harness:init:
    dir: "{{.USER_WORKING_DIR}}"
    vars:
      OCI: quay.io/ncdv/d3-tools:harness-0.0.1
    cmds:
      - "{{.CTN}} run --rm -v ./:/usr/src/app {{.OCI}}"

  software-hub:
    cmds:
      - "distrobox enter software-hub"

  dev-shell:
    cmds:
      - "toolbox enter dev-shell"

  pkg:bk:
    dir: /home/doku/onedrive/backup/dotfiles/
    vars:
      DST: /home/doku/onedrive/backup/dotfiles/
      HOME: /home/doku/
      AUR: "pacman-aur"
      NATIVE: "pacman-native"
    cmds:
      - "pacman -Qqen > {{.DST}}{{.AUR}}.txt"
      - "pacman -Qqem > {{.DST}}{{.NATIVE}}.txt"
      - "cp {{.HOME}}/Taskfile.yml {{.DST}}"
      - 'git add . && git commit -m "backup arch pkgs"'
      - "git push origin main"
