preload = /var/home/doku/Pictures/wallpapers/racoon.png

# set the wallpaper for each monitor
wallpaper = eDP-1,/var/home/doku/Pictures/wallpapers/racoon.png
wallpaper = DP-1,/var/home/doku/Pictures/wallpapers/racoon.png

# disable messages on bottom
splash = false
